### ISSUE TITLE
Installer doesn't work on Kubernetes 1.22+

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrantctl#27]
The installer uses deprecated versions of CRDs that were removed in 1.22, these include:
* `admissionregistration.k8s.io/v1beta1`
* `apiextensions.k8s.io/v1beta1`
* `admissionregistration.k8s.io/v1beta1`

There might be more deprecated CRDs used, but these are the ones I noticed.

**Comment by eguzki** [comment]
Thanks @pehala ! we will fix that
