### ISSUE TITLE
Kuadrant cannot be installed on OpenShift

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrantctl#28]
Currently, the Istiod won't be deployed as it requires additional permissions to be installed on OpenShift (https://istio.io/latest/docs/setup/platform-setup/openshift/), specifically this command to be run beforehand:
`oc adm policy add-scc-to-group anyuid system:serviceaccounts:kuadrant-system`

**Comment by david-martin** [comment]
@eguzki this no longer relevant since [install cmd removed](https://github.com/Kuadrant/kuadrantctl/pull/70)?
