### ISSUE TITLE
kuadrantctl version returns "latest" instead of version number

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/kuadrantctl#69]
In version `v0.2.0` it was not the case but now in `v0.2.2` it is.
```
$ kuadrantctl version
{"level":"info","ts":"2024-05-02T15:38:22+02:00","msg":"kuadrantctl version: latest"}
```

**Comment by ehearneRedHat** [comment]
https://github.com/Kuadrant/kuadrantctl/commit/a1101811141c02a22ae56749effa9e55fdfd29fa

**Comment by ehearneRedHat** [comment]
@azgabur let me know if this issue has been resolved when you have the chance. :)
