### ISSUE TITLE
Format of version command

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrantctl#90]
Currently the format looks like this:
`{"level":"info","ts":"2024-06-24T08:58:28+02:00","msg":"kuadrantctl version: v0.2.3"}`
While the format does convey the actual version, it has a few small issues:
1) For some reason we have request date and log level as well even though they are not that relevant
2) It is outputted in `stderr` instead of `stdout`
3) The actual result is under `msg` key and in string format
    * This makes it unnecessarily hard to programmatically parse the version

**Comment by ehearneRedHat** [comment]
Hi @pehala ,

I can see the first two can be resolved quite easily, but I am unsure how to resolve the third. 

My proposed solution would be to add another field simply called `version` . So, once it is stdout, and no timestamp/log level, the output could look like 

`{"version": "v0.2.3", "msg": "kuadrantctl version: v0.2.3"}` 

Of course, we could just remove `msg` and use `version` instead, but I am thinking of the usecase of programatically parsing the version, and maybe we want to let the user know that it is `kuadrantctl` that they are getting the version from? 

Let me know your thoughts. :)

**Comment by pehala** [comment]
I think t

> My proposed solution would be to add another field simply called `version` . So, once it is stdout, and no timestamp/log level, the output could look like
> 
> `{"version": "v0.2.3", "msg": "kuadrantctl version: v0.2.3"}`

I like that solution a lot! Covers all usecases nicely :)

**Comment by ehearneRedHat** [comment]
@pehala Awesome, I'll get on it. :)

**Comment by ehearneRedHat** [comment]
Closing as version command on `main` meets most of the specified requirements. 

```bash
$ ./bin/kuadrantctl version
kuadrantctl v0.2.4-dev (64f6301)
```

**Comment by ehearneRedHat** [comment]
We have decided not to go forward with the third proposal for now.
